/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    stories: Story;
    photos: Photo;
    teams: Team;
    competitions: Competition;
    tags: Tag;
    bookings: Booking;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {
    impressum: Impressum;
    datenschutz: Datenschutz;
    settings: Setting;
    aboutPage: AboutPage;
  };
  globalsSelect: {
    impressum: ImpressumSelect<false> | ImpressumSelect<true>;
    datenschutz: DatenschutzSelect<false> | DatenschutzSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Foto-Stories — Kern des Portfolios
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  /**
   * Gemeinsamer Slug für DE/EN (z. B. vcw-sc-potsdam-2025)
   */
  slug: string;
  title: string;
  competition?: (number | null) | Competition;
  homeTeam?: (number | null) | Team;
  awayTeam?: (number | null) | Team;
  venue?: string | null;
  playedAt?: string | null;
  result?: string | null;
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?:
    | (
        | FullBleedPhotoBlock
        | DiptychBlock
        | TriptychBlock
        | InsetPortraitBlock
        | SequenceBlock
        | PullQuoteBlock
        | TextParagraphBlock
      )[]
    | null;
  coverPhoto?: (number | null) | Photo;
  featured?: boolean | null;
  featuredOrder?: number | null;
  published?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: number;
  name: string;
  season: string;
  tier?: ('bundesliga' | '2-bundesliga' | 'regional' | 'youth') | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  shortName?: string | null;
  city?: string | null;
  tier?: ('bundesliga' | '2-bundesliga' | 'regional' | 'youth') | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullBleedPhotoBlock".
 */
export interface FullBleedPhotoBlock {
  photo: number | Photo;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fullBleedPhoto';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leer lassen für reine Highlight-Fotos
   */
  story?: (number | null) | Story;
  tags?: (number | Tag)[] | null;
  isHighlight?: boolean | null;
  isCover?: boolean | null;
  orderInStory?: number | null;
  watermark?: ('none' | 'light' | 'standard') | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feed?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DiptychBlock".
 */
export interface DiptychBlock {
  photoLeft: number | Photo;
  photoRight: number | Photo;
  ratio?: ('50-50' | '60-40') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'diptych';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TriptychBlock".
 */
export interface TriptychBlock {
  photos: (number | Photo)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'triptych';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsetPortraitBlock".
 */
export interface InsetPortraitBlock {
  photo: number | Photo;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insetPortrait';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SequenceBlock".
 */
export interface SequenceBlock {
  photos: (number | Photo)[];
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sequence';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  quote: string;
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextParagraphBlock".
 */
export interface TextParagraphBlock {
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textParagraph';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  name: string;
  email: string;
  organization?: string | null;
  message: string;
  locale: 'de' | 'en';
  /**
   * Neon Auth user id (null for anonymous submissions).
   */
  customerId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'competitions';
        value: number | Competition;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  competition?: T;
  homeTeam?: T;
  awayTeam?: T;
  venue?: T;
  playedAt?: T;
  result?: T;
  summary?: T;
  layout?:
    | T
    | {
        fullBleedPhoto?: T | FullBleedPhotoBlockSelect<T>;
        diptych?: T | DiptychBlockSelect<T>;
        triptych?: T | TriptychBlockSelect<T>;
        insetPortrait?: T | InsetPortraitBlockSelect<T>;
        sequence?: T | SequenceBlockSelect<T>;
        pullQuote?: T | PullQuoteBlockSelect<T>;
        textParagraph?: T | TextParagraphBlockSelect<T>;
      };
  coverPhoto?: T;
  featured?: T;
  featuredOrder?: T;
  published?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullBleedPhotoBlock_select".
 */
export interface FullBleedPhotoBlockSelect<T extends boolean = true> {
  photo?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DiptychBlock_select".
 */
export interface DiptychBlockSelect<T extends boolean = true> {
  photoLeft?: T;
  photoRight?: T;
  ratio?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TriptychBlock_select".
 */
export interface TriptychBlockSelect<T extends boolean = true> {
  photos?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsetPortraitBlock_select".
 */
export interface InsetPortraitBlockSelect<T extends boolean = true> {
  photo?: T;
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SequenceBlock_select".
 */
export interface SequenceBlockSelect<T extends boolean = true> {
  photos?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock_select".
 */
export interface PullQuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextParagraphBlock_select".
 */
export interface TextParagraphBlockSelect<T extends boolean = true> {
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  story?: T;
  tags?: T;
  isHighlight?: T;
  isCover?: T;
  orderInStory?: T;
  watermark?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feed?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  city?: T;
  tier?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  name?: T;
  season?: T;
  tier?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  organization?: T;
  message?: T;
  locale?: T;
  customerId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum".
 */
export interface Impressum {
  id: number;
  legalName: string;
  addressLine1: string;
  addressLine2?: string | null;
  postalCode: string;
  city: string;
  country: string;
  email: string;
  phone?: string | null;
  ustIdNr?: string | null;
  responsibleForContent?: string | null;
  additionalNotes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutz".
 */
export interface Datenschutz {
  id: number;
  title: string;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lastUpdated: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  defaultWatermark?: boolean | null;
  accentColor?: string | null;
  homeFeaturedCount?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: number;
  sections?: (PageHeaderBlock | PortraitFigureBlock | EditorialProseBlock | CtaLinkBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock".
 */
export interface PageHeaderBlock {
  label?: string | null;
  title: string;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortraitFigureBlock".
 */
export interface PortraitFigureBlock {
  photo?: (number | null) | Photo;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portraitFigure';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EditorialProseBlock".
 */
export interface EditorialProseBlock {
  eyebrow?: string | null;
  title?: string | null;
  body1?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pullQuote?: string | null;
  body2?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  credits?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'editorialProse';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaLinkBlock".
 */
export interface CtaLinkBlock {
  label: string;
  target: '/contact' | '/about' | '/athletes' | '/services' | '/highlights' | '/stories' | '/';
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaLink';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum_select".
 */
export interface ImpressumSelect<T extends boolean = true> {
  legalName?: T;
  addressLine1?: T;
  addressLine2?: T;
  postalCode?: T;
  city?: T;
  country?: T;
  email?: T;
  phone?: T;
  ustIdNr?: T;
  responsibleForContent?: T;
  additionalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutz_select".
 */
export interface DatenschutzSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  body?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  defaultWatermark?: T;
  accentColor?: T;
  homeFeaturedCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        pageHeader?: T | PageHeaderBlockSelect<T>;
        portraitFigure?: T | PortraitFigureBlockSelect<T>;
        editorialProse?: T | EditorialProseBlockSelect<T>;
        ctaLink?: T | CtaLinkBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock_select".
 */
export interface PageHeaderBlockSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortraitFigureBlock_select".
 */
export interface PortraitFigureBlockSelect<T extends boolean = true> {
  photo?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EditorialProseBlock_select".
 */
export interface EditorialProseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  body1?: T;
  pullQuote?: T;
  body2?: T;
  credits?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaLinkBlock_select".
 */
export interface CtaLinkBlockSelect<T extends boolean = true> {
  label?: T;
  target?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}